name: voice_crm_ui_upgrade
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0 # For date formatting
  flutter_svg: ^2.0.10+1 # If you want to use custom SVG icons (e.g., Lucide)
  font_awesome_flutter: ^10.7.0 # For Plus, Mic, and X icons
  flutter_animate: ^4.5.0       # For staggered entry animations on tags
  uuid: ^4.4.0 # Keep this for ID generation if you use it for new notes
  path_provider: ^2.1.3 # Needed to find a suitable directory for the database

  # Isar database
  isar: ^3.0.5 # Or the latest stable version
  isar_flutter_libs: ^3.0.5 # Native libs for Isar
  #isar: ^4.0.0-dev.14
  #isar_flutter_libs: ^4.0.0-dev.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

 
  # isar_generator:
  #   git:
  #     url: https://github.com/Kiruel/isar
  #     ref: fix/web_build
  #     path: packages/isar_generator

  # Code generator for Isar
  isar_generator: ^3.1.0+1 # Or the latest stable version
  build_runner: ^2.4.6 # Or the latest stable version

# dependency_overrides:
#   isar_generator:
#     git:
#       url: https://github.com/Kiruel/isar
#       ref: fix/web_build
#       path: packages/isar_generator


flutter:
  uses-material-design: true
  fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf
      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter-SemiBold.ttf
        weight: 600
assets:
  # Add your font assets here. Create an 'assets/fonts' folder in your project root.
  - assets/fonts/


